---
title: "Desafio06"
author: "Rafael Machado de Almeida Garibalde - 277225"
format: html
editor: visual
---

```{r}
path <- "~/ME315"
fname <- file.path(path, "disco.db")
print(fname)

```

```{r}
library(RSQLite)
conn <- dbConnect(SQLite(), fname)
tabelas <- dbListTables(conn)
print(tabelas)


colunas_customers <- dbListFields(conn, "customers")
print(colunas_customers)


dbGetQuery(conn, "SELECT COUNT(*) AS total_clientes FROM customers;")
total.clientes <- dbGetQuery(conn, "SELECT COUNT(*) AS total_clientes FROM customers;")[[1]]
total.clientes

dbGetQuery(conn, "SELECT COUNT(DISTINCT Country) AS total_paises FROM customers;")
total.países <- dbGetQuery(conn, "SELECT COUNT(DISTINCT Country) AS total_paises FROM customers;")[[1]]
total.países


dbGetQuery(conn,"SELECT Country, COUNT(*) AS total_clientes FROM customers GROUP BY Country ORDER BY total_clientes DESC;")


dbGetQuery(conn, "SELECT Country, COUNT(*) AS total_clientes FROM customers GROUP BY Country ORDER BY total_clientes DESC LIMIT 5;")


dbGetQuery(conn, "SELECT DISTINCT Country FROM customers WHERE LENGTH(Country)=6;")


dbGetQuery(conn, "SELECT tracks.Name FROM customers JOIN invoices ON customers.CustomerId = invoices.CustomerId JOIN invoice_items ON invoices.InvoiceId = invoice_items.InvoiceId JOIN tracks ON invoice_items.TrackId = tracks.TrackId WHERE customers.Country = 'Brazil';")


### Qual o álbum mais tocado por pais?
dbGetQuery(conn, "SELECT Country, Title AS Album, Total FROM (SELECT customers.Country, albums.Title, COUNT(*) AS Total, ROW_NUMBER() OVER(PARTITION BY customers.Country ORDER BY COUNT(*) DESC) AS rn FROM customers JOIN invoices ON customers.CustomerId = invoices.CustomerId JOIN invoice_items ON invoices.InvoiceId = invoice_items.InvoiceId JOIN tracks ON invoice_items.TrackId = tracks.TrackId JOIN albums ON tracks.AlbumId = albums.AlbumId GROUP BY customers.Country, albums.Title) WHERE rn=1;")



### Qual o artista mais tocado por pais?
dbGetQuery(conn, "SELECT Country, Name AS Artista, Total FROM (SELECT customers.Country, artists.Name, COUNT(*) AS Total, ROW_NUMBER() OVER(PARTITION BY customers.Country ORDER BY COUNT(*) DESC) AS rn FROM customers JOIN invoices ON customers.CustomerId = invoices.CustomerId JOIN invoice_items ON invoices.InvoiceId = invoice_items.InvoiceId JOIN tracks ON invoice_items.TrackId = tracks.TrackId JOIN albums ON tracks.AlbumId = albums.AlbumId JOIN artists ON albums.ArtistId = artists.ArtistId GROUP BY customers.Country, artists.Name) WHERE rn=1;")

dbDisconnect(conn)
```
